- hosts: webservers
  
  tasks:

  - name: install httpd
    package:
       name: "httpd"
       state: present

  - copy:
       src: "index.php"
       dest: "/var/www/html"

  - package:
       name: "php"
       state: present

  - name: start httpd
    service: 
       name: "httpd"
       state: "started"
       enabled: yes
  
  - firewalld:
       port: "80/tcp"
       state: enabled
       permanent: yes
       immediate: yes
  
- hosts: loadbalancer
  vars_prompt:
        - name: portnumber
          private: no
          prompt: "enter the port number for website"
       
  tasks:
  
  - name: install haproxy
    package:
        name: "haproxy"
        state: present


  - template:
      dest: "/etc/haproxy/haproxy.cfg"
      src: "haproxy.cfg.j2"


  - name: start haproxy
    service: 
       name: "haproxy"
       state: "started"
       enabled: yes


  - firewalld:
       port: "8080/tcp"
       state: enabled
       permanent: yes
       immediate: yes
  
  

