- hosts: 192.168.43.59,192.168.43.53,192.168.43.54
  
  tasks:
  - name: copying jdk
    copy:
      dest: "/root"
      src: "/root/jdk-8u171-linux-x64.rpm"
      
  - name: copying hadoop
    copy:
      dest: "/root"
      src: "/root/hadoop-1.2.1-1.x86_64.rpm"

  - name: installing jdk
    command: "rpm -i jdk-8u171-linux-x64.rpm"

  - name: installing hadoop
    command: "rpm -i hadoop-1.2.1-1.x86_64.rpm --force"
